export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta name="description" content="Generated by Mike van Peeren" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
