import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="px-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-2 flex flex-1 flex-col justify-center items-center min-h-screen">
        <h1 className="m-0 text-7xl text-center text-indigo-500 hover:underline focus:underline">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className="text-center my-16 text-2xl">
          Get started by editing{" "}
          <code className="bg-gray-100 rounded-2xl p-3 text-base">
            pages/index.js
          </code>
        </p>
        {/* margin: 1rem; padding: 1.5rem; text-align: left; color: inherit;
        text-decoration: none; border: 1px solid #eaeaea; border-radius: 10px;
        transition: color 0.15s ease, border-color 0.15s ease; max-width: 300px; */}
        <div className="flex items-center justify-center flex-wrap max-w-3xl md:flex-unset">
          <a
            href="https://nextjs.org/docs"
            className="p-6 m-4 text-left no-underline border rounded-md transition-colors ease-in-out duration-700 max-w-xs hover:text-indigo-500 hover:border-indigo-500 min-h-[200px]"
          >
            <h2 className="text-2xl mb-8">Documentation &rarr;</h2>
            <p className="m-0 text-xl">
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn"
            className="p-6 m-4 text-left no-underline border rounded-md transition-colors ease-in-out duration-700 max-w-xs hover:text-indigo-500 hover:border-indigo-500 min-h-[200px]"
          >
            <h2 className="text-2xl mb-8">Learn &rarr;</h2>
            <p className="m-0 text-xl">
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="p-6 m-4 text-left no-underline border rounded-md transition-colors ease-in-out duration-700 max-w-xs hover:text-indigo-500 hover:border-indigo-500 min-h-[200px]"
          >
            <h2 className="text-2xl mb-8">Examples &rarr;</h2>
            <p className="m-0 text-xl">
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="p-6 m-4 text-left no-underline border rounded-md transition-colors ease-in-out duration-700 max-w-xs hover:text-indigo-500 hover:border-indigo-500 min-h-[200px]"
          >
            <h2 className="text-2xl mb-8">Deploy &rarr;</h2>
            <p className="m-0 text-xl">
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <footer className="w-full h-[100px] flex justify-center items-center border">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className="flex justify-center items-center"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="h-5 ml-2">
            <Image
              className="ml-2"
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
